# Generated by Django 3.1.7 on 2021-04-05 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('beauty', 'beauty'), ('fasion', 'fashion and style')], max_length=125)),
                ('image', models.ImageField(upload_to='sliders')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('description', models.TextField()),
                ('isTrending', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('beauty', 'beauty'), ('fasion', 'fashion and style')], max_length=124)),
                ('image', models.ImageField(upload_to='news_thumbnail')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
